services:
  live-browser:
    image: lscr.io/linuxserver/chromium:latest
    container_name: live-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
      - CUSTOM_USER=${LIVE_BROWSER_USER}
      - PASSWORD=${LIVE_BROWSER_PASSWORD}
    volumes:
      - live-browser-config:/config
    shm_size: "1gb"
    restart: unless-stopped
    ports:
      - "3010:3000"
      - "3011:3001"

volumes:
  live-browser-config:
